


url: http://takagotch.github.io/page55/
baseurl: https://takagotch/github.io/page55/

title: Takagotch Officail site
# title_separator:
# subtitle:
# name
#
email: yoshioka.takashi@outlook.com
description: This an awesome official page for your new site here.

theme: 
skin: 
locale: 
logo:
date_format:
read_time:
words_per_minute:
mathjax:
  enable:
  combo:
  tags:
google_fonts:
  - name: 
    weights: ""
google_analytics:
disqus:
  shortname:
  

pepole:
- name: Takashi Yoshioka
  pic:
  position:
  socail:
   - title: 
     url:
     
socail:
  - title: facebook 
    url:   http://facebook.com/takagotch/
  - title: github
    url:   http://github.com/takagotch/

address:
  - line: NankoKita wtc tower 55
  - line: Namba, Osaka, JP
  
markdown: kramdown
permalink: pretty





